version: "3"
services:
  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_DB: question_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: question_db
    ports:
      - 5432:5432
    expose:
      - 5432

  db_test:
    image: postgres:11.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: question_db_test
    container_name: question_db_test
    ports:
      - 5438:5432